services:

  wordpress:
    build: .
    image: wordpress
    restart: always
    ports:
      - 6080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test_user
      WORDPRESS_DB_PASSWORD: test_pass
      WORDPRESS_DB_NAME: test_db
    volumes:
      - ./wordpress:/var/www/html
    x-develop:
      watch:
        - action: sync
          path: ./wordpress
          target: /var/www/html

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 6036:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
